name: Print Info

on:
  push:
    branches:
      - main

jobs:
  print_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Puedes especificar aquí la versión de Node.js que quieres usar

      - name: Print Information
        run: |
          echo "Nombre Completo: José Juan Díaz"
          node --version
          echo "Expediente: 740313"
